# Generated by Django 4.2.2 on 2023-09-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Ingredient",),
        migrations.DeleteModel(name="IngredientSubCategory",),
    ]
